### PR TITLE
Troubleshoot Travis build fail

### PR DESCRIPTION
**Pull request by misselbeck**
**This PR does the following:**

- Moved all devDependencies to dependencies in the `package.json` file

### CODE REVIEW

**Comment by misselbeck** [comment]
- Updated dependencies as part of troubleshooting Travis build fail
- Found that the outdated webpack config/sass-loader was having an issue compiling a sourceMap from a particular file from the new header-component. There is a [related issue](https://github.com/webpack-contrib/sass-loader/issues/351) in the sass-loader repo.
- Turned off sourceMaps for now as that is a primarily a local dev tool. Travis build now passing.
- Recommend updating the webpack version, config and loader dependencies in the future.

**Comment by EdwinGuzman** [comment]
@misselbeck do you recommend updating the webpack version, config, and loader deps in this repo or in the header?

**Review by EdwinGuzman — APPROVED** [review]
Update installs, builds, and runs well. Thanks.

**Comment by misselbeck** [comment]
> @misselbeck do you recommend updating the webpack version, config, and loader deps in this repo or in the header?

I would say this repo...since this is still using Webpack v1.

**Pull request merged**
